version: "3.9"

services:
  civicstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: civicstack:latest
    container_name: civicstack
    ports:
      - "8050:8050"
    restart: unless-stopped
