version: "3.9"

services:
  civicstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: civicstack:latest
    container_name: civicstack_local
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8050
