version: "3.9"

services:
  civicstack:
    build:
      context: .
      dockerfile: Dockerfile
    image: civicstack:latest
    container_name: civicstack
    ports:
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    restart: unless-stopped
    command: python3 main.py
