version: "3.9"

services:
  weavr_agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: weavr_agent:latest
    container_name: weavr_agent
    ports:
      - "5151:5151" # Exposes WEAVR Agent on VPS
    volumes:
      - ./output:/app/output
      - ./agents/weavr_agent/.env.sample:/app/agents/weavr_agent/.env
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_models:
