version: "3.9"

services:
  weavr_agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: weavr_agent:latest
    container_name: weavr_agent
    ports:
      - "5151:5151"  # Exposes WEAVR agent externally
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
