services:
  weavr_agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: weavr_agent:latest
    container_name: weavr_agent
    ports:
      - "5151:5151"  # ← MAKE SURE THIS EXISTS
    volumes:
      - ./output/app:/app/output
    restart: unless-stopped
    depends_on:
      - ollama

  civicstack:
    build:
      context: ./weavr/stacks/civicstack
      dockerfile: Dockerfile
    image: civicstack:latest
    container_name: civicstack
    ports:
      - "8050:8050"  # ← ADD THIS IF MISSING
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama_data:/data

volumes:
  ollama_data:
    driver: local
