version: "3.9"

services:
  weavr_agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: weavr_agent:latest
    container_name: weavr_agent
    ports:
      - target: 5151
        published: 5151
        protocol: tcp
        mode: host
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    depends_on:
      - ollama
    command: uvicorn app.agents.weavr_agent.weavr_core:app --host 0.0.0.0 --port 5151

  civicstack:
    build:
      context: ./weavr/stacks/civicstack
      dockerfile: Dockerfile
    image: civicstack:latest
    container_name: civicstack
    ports:
      - target: 8050
        published: 8050
        protocol: tcp
        mode: host
    restart: unless-stopped
    command: python3 main.py

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - target: 11434
        published: 11434
        protocol: tcp
        mode: host
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
    driver: local
